/**
 * Fetches Nikolas Murdock's albums from Spotify + Apple Music URLs,
 * then writes src/data/albums.ts.
 *
 * Reads credentials from .env.local (SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET).
 * Run with: npm run fetch-spotify
 *
 * New albums are added. Existing entries are preserved so manual edits survive.
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_FILE = path.join(__dirname, "../src/data/albums.ts");
const ENV_FILE = path.join(__dirname, "../.env.local");

const ARTIST_ID = "4TAI8CNL9UNLAZ4dYagwws";
const ARTIST_NAME = "Nikolas Murdock";

// ── Load .env.local ──────────────────────────────────────────────
function loadEnv() {
  if (!fs.existsSync(ENV_FILE)) return;
  for (const line of fs.readFileSync(ENV_FILE, "utf8").split("\n")) {
    const [key, ...rest] = line.split("=");
    if (key && rest.length) process.env[key.trim()] = rest.join("=").trim();
  }
}

// ── Spotify ──────────────────────────────────────────────────────
async function getAccessToken() {
  const clientId = process.env.SPOTIFY_CLIENT_ID;
  const clientSecret = process.env.SPOTIFY_CLIENT_SECRET;
  if (!clientId || !clientSecret) {
    throw new Error("Missing SPOTIFY_CLIENT_ID or SPOTIFY_CLIENT_SECRET in .env.local");
  }
  const res = await fetch("https://accounts.spotify.com/api/token", {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      Authorization: `Basic ${Buffer.from(`${clientId}:${clientSecret}`).toString("base64")}`,
    },
    body: "grant_type=client_credentials",
  });
  if (!res.ok) throw new Error(`Spotify token error ${res.status}: ${await res.text()}`);
  const data = await res.json();
  if (!data.access_token) throw new Error(`No access token: ${JSON.stringify(data)}`);
  return data.access_token;
}

async function fetchWithRetry(url, options, retries = 4) {
  for (let i = 0; i <= retries; i++) {
    const res = await fetch(url, options);
    if (res.status === 429) {
      const retryAfter = parseInt(res.headers.get("Retry-After") ?? "10", 10);
      const wait = (retryAfter + 1) * 1000;
      console.log(`  Rate limited — waiting ${retryAfter + 1}s before retry ${i + 1}/${retries}...`);
      await new Promise((r) => setTimeout(r, wait));
      continue;
    }
    return res;
  }
  throw new Error("Exceeded retry limit due to Spotify rate limiting.");
}

async function fetchAlbums(token) {
  const headers = { Authorization: `Bearer ${token}` };
  const items = [];
  let url = `https://api.spotify.com/v1/artists/${ARTIST_ID}/albums?include_groups=album,single,ep`;
  while (url) {
    const res = await fetchWithRetry(url, { headers });
    if (!res.ok) throw new Error(`Spotify albums error ${res.status}: ${await res.text()}`);
    const data = await res.json();
    items.push(...(data.items ?? []));
    url = data.next ?? null;
  }
  return items.sort((a, b) => (a.release_date < b.release_date ? 1 : -1));
}

// ── Apple Music ──────────────────────────────────────────────────
async function getAppleMusicUrl(albumName) {
  const query = encodeURIComponent(`${ARTIST_NAME} ${albumName}`);
  const res = await fetch(`https://itunes.apple.com/search?term=${query}&entity=album&limit=3`);
  if (!res.ok) return null;
  const data = await res.json();
  const match = data.results?.find((r) =>
    r.collectionName.toLowerCase().includes(albumName.toLowerCase())
  );
  return match?.collectionViewUrl ?? null;
}

// ── Load existing albums to detect new ones ──────────────────────
function loadExistingIds() {
  if (!fs.existsSync(OUT_FILE)) return new Set();
  const src = fs.readFileSync(OUT_FILE, "utf8");
  const ids = new Set();
  for (const match of src.matchAll(/spotifyId:\s*"([^"]+)"/g)) ids.add(match[1]);
  return ids;
}

// ── Main ─────────────────────────────────────────────────────────
loadEnv();

console.log("Fetching Spotify token...");
const token = await getAccessToken();

console.log("Fetching albums...");
const albums = await fetchAlbums(token);
console.log(`  Found ${albums.length} releases on Spotify`);

console.log("Fetching Apple Music URLs...");
const appleMusicUrls = Object.fromEntries(
  await Promise.all(albums.map(async (a) => [a.id, await getAppleMusicUrl(a.name)]))
);

const existingIds = loadExistingIds();
const newAlbums = albums.filter((a) => !existingIds.has(a.id));
if (newAlbums.length > 0) {
  console.log(`  🆕 New releases: ${newAlbums.map((a) => a.name).join(", ")}`);
} else {
  console.log("  No new releases since last fetch.");
}

// ── Write file ───────────────────────────────────────────────────
const lines = [
  `// Auto-generated by scripts/fetch-spotify.mjs — run \`npm run fetch-spotify\` to update.`,
  `// Commit this file so Vercel never needs to call Spotify at build/request time.`,
  ``,
  `export interface Album {`,
  `  spotifyId: string;`,
  `  name: string;`,
  `  releaseDate: string;`,
  `  albumType: string;`,
  `  totalTracks: number;`,
  `  image: string;`,
  `  spotifyUrl: string;`,
  `  appleMusicUrl: string | null;`,
  `}`,
  ``,
  `export const albums: Album[] = [`,
];

for (const a of albums) {
  lines.push(`  {`);
  lines.push(`    spotifyId: ${JSON.stringify(a.id)},`);
  lines.push(`    name: ${JSON.stringify(a.name)},`);
  lines.push(`    releaseDate: ${JSON.stringify(a.release_date)},`);
  lines.push(`    albumType: ${JSON.stringify(a.album_type)},`);
  lines.push(`    totalTracks: ${a.total_tracks},`);
  lines.push(`    image: ${JSON.stringify(a.images[0]?.url ?? "")},`);
  lines.push(`    spotifyUrl: ${JSON.stringify(a.external_urls.spotify)},`);
  lines.push(`    appleMusicUrl: ${JSON.stringify(appleMusicUrls[a.id] ?? null)},`);
  lines.push(`  },`);
}

lines.push(`];`);
lines.push(``);

fs.writeFileSync(OUT_FILE, lines.join("\n"), "utf8");
console.log(`\n✅ Written to src/data/albums.ts (${albums.length} releases)`);
