// Auto-generated by scripts/fetch-spotify.mjs — run `npm run fetch-spotify` to update.
// Commit this file so Vercel never needs to call Spotify at build/request time.

export interface Album {
  spotifyId: string;
  name: string;
  releaseDate: string;
  albumType: string;
  totalTracks: number;
  image: string;
  spotifyUrl: string;
  appleMusicUrl: string | null;
}

export const albums: Album[] = [];
